### ISSUE TITLE
How to generate vapid keys for this Chart?

### ISSUE THREAD

**Issue by J0n4t4n** [mastodon/chart#29]
Hi all,
I tried installing Mastodon using this chart and it requires me to set the vapid private_key and public_key.
Now according to the normal installation instructions on the mastodon website one can do this using the "mastodon:webpush:generate_vapid_key" command, after installing the packages, which doesn't really work when deploying to Kubernetes with Helm.
I would assume that it is possible to run the generate command inside one of the containers, but as I don't yet have a deep understanding of Mastodon I don't know which one.
I think it would be great if on the README you could provide a one-shot "kubectl run ..." command that uses the correct container image and generates these keys, such that newcomers like me know how to generate them in the Helm setup :)

**Comment by mschneider82** [comment]
i have the same issue

**Comment by mschneider82** [comment]
To generate keys for VAPID_PRIVATE_KEY & VAPID_PUBLIC_KEY run:

```
docker run --rm -it -w /app/www --entrypoint rake lscr.io/linuxserver/mastodon mastodon:webpush:generate_vapid_key
```

**Comment by deepy** [comment]
Why not use the official docker image from `tootsuite/mastodon`?

**Comment by mschneider82** [comment]
because i found this in an documentation, it worked well for me = problem solved. just wanted to share the solution. Feel free to modify it with the official image und add it to readme.

**Comment by J0n4t4n** [comment]
Thanks a lot, that was enough information to get me onto the right path.

Here are the `kubectl run` commands to generate the secret and keys using the official image:


```bash
kubectl run -i --rm --attach mastodonkeys --image=tootsuite/mastodon --command -- bundle exec rake secret
```

```bash
kubectl run -i --rm --attach mastodonkeys --image=tootsuite/mastodon --command -- bundle exec rake mastodon:webpush:generate_vapid_key
```

Had to add "bundle exec", as otherwise I received this error:
```bash
Gem::LoadError: You have already activated rake 13.0.3, but your Gemfile requires rake 13.0.6. Prepending `bundle exec` to your command may solve this.
```

I think it would be great to add them to the README, such that people know how to generate them.
