### ISSUE TITLE
streaming service ingress path should match mastodon documentation

### ISSUE THREAD

**Issue by mkhl** [mastodon/chart#36]
the [mastodon api documentation](https://docs.joinmastodon.org/methods/timelines/streaming/) states the streaming api websocket endpoint is `/api/v1/streaming`
but the [ingress template of this chart](https://github.com/mastodon/chart/blob/ae892d539ed35433ceadeadaf87113cca75c2ea7/templates/ingress.yaml#L55) only forwards `/api/v1/streaming/` to the service.

this came up in mastodon too (discussion at mastodon/mastodon#19872, patch at mastodon/mastodon#19896), and breaks some clients (elk, pinafore nolanlawson/pinafore#2161) that follow the documentation, but not the default mastodon frontend or glitch.social which both use the undocumented `/api/v1/streaming/` directly.

**Comment by Cardes** [comment]
This also only works correct on openshift routes without the trailing slash for the streaming url.
